#!/usr/bin/env sh

#2 try

# auto app placement

yabai -m rule --add app="Visual Studio Code" space=1
yabai -m rule --add app="WPS Office" space=1

yabai -m rule --add app=Arc space=2

yabai -m rule --add app="GitHub Desktop" space=3
yabai -m rule --add app=Postman space=3

yabai -m rule --add app=WeCom space=4
yabai -m rule --add app=WeChat space=4
yabai -m rule --add app=QQ space=4

yabai -m rule --add app=Notion space=5
yabai -m rule --add app="Microsoft Edge" space=5
yabai -m rule --add app=Safari space=5

yabai -m rule --add app=Notes space=11
yabai -m rule --add app=Calendar space=11
yabai -m rule --add app=Reminders space=11
yabai -m rule --add app=Typora space=11
yabai -m rule --add app=Spotify space=11

# borders
# yabai -m config window_border                on
# yabai -m config active_window_border_topmost on
# yabai -m config window_shadow                on
# yabai -m config window_border_width          5
# yabai -m config active_window_border_color   0xffff3050
# yabai -m config normal_window_border_color   0xffaaaaaa

# general space settings
# yabai -m config layout                       bsp

# yabai -m config top_padding                  6
# yabai -m config bottom_padding               6
# yabai -m config left_padding                 25
# yabai -m config right_padding                25
# yabai -m config window_gap                   5
