#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# config
yabai -m config                                \
    window_placement            second_child   \
    split_ratio                 0.5            \
    auto_balance                off            \
    # top_padding                 8              \
    # bottom_padding              8              \
    # left_padding                8              \
    # right_padding               8              \
    window_gap                  8              \
    layout                      bsp

# space setup
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 code
setup_space 2 web
setup_space 3 git
setup_space 4 social
setup_space 5 media
setup_space 6 other

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# auto app placement
yabai -m rule --add app="Visual Studio Code" space=1
yabai -m rule --add app=Arc space=2
yabai -m rule --add app="GitHub Desktop" space=3
yabai -m rule --add app=WeCom space=4
yabai -m rule --add app=WeChat space=4
yabai -m rule --add app=QQ space=4
yabai -m rule --add app="Microsoft Edge" space=5
yabai -m rule --add app=Safari space=5
yabai -m rule --add app=Notion space=5
