global_vars:
  - name: "clipboard"  # https://espanso.org/docs/matches/extensions/#clipboard-extension
    type: "clipboard"

matches:
  - trigger: ":full code"
    replace: "full code without omit anything"

  - trigger: ":2console"
    replace: "remove types and exports, make them can be run in browser console: {{clipboard}}"

  - trigger: ":exp"
    replace: "下面的代码是用来干什么的，请详细解释，加上行内注释: {{clipboard}}"

  - trigger: ":td"
    replace: "{{today_date}} "
    vars:
      - name: today_date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":todo"
    replace: "🎏 {{today_date}} Todos\n-"
    vars:
      - name: today_date
        type: date
        params:
          format: "%Y-%m-%d"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
