live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml"
  # "~/.config/alacritty/themes/themes/hyper.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[font]
size = 18

[window]
padding.x = 16
padding.y = 14
decorations = "buttonless"
opacity = 0.9

