live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml"
  # "~/.config/alacritty/themes/themes/hyper.toml"
]

# https://github.com/basecamp/omakub/tree/master/defaults/alacritty

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/zellij"

[font]
size = 18
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

[window]
padding.x = 16
padding.y = 14
decorations = "buttonless"
opacity = 0.98

